// Shared DB helper. Deliberately not a connection pool — this is a
// low-traffic internal tool (Neon's free plan is plenty), and the brief
// asks for no pooling infrastructure on top of Neon. Each call opens a
// short-lived `pg` client, runs its query, and closes it. Works against
// Neon (standard Postgres wire protocol, sslmode=require) or any plain
// Postgres, including localhost for dev/testing.
import pg from "pg";

function makeClient() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) throw new Error("DATABASE_URL is not set");
  return new pg.Client({
    connectionString,
    ssl: /neon\.tech|sslmode=require/.test(connectionString) ? { rejectUnauthorized: false } : false,
  });
}

async function withClient(fn) {
  const client = makeClient();
  await client.connect();
  try {
    return await fn(client);
  } finally {
    await client.end();
  }
}

// created_at/updated_at are tracked by the row (see db/schema.sql), not
// inside the `data` JSONB blob — merging them onto the returned object here
// is the one place that happens, so every reader (the frontend, buildPreview,
// etc.) sees them as plain `createdAt`/`updatedAt` fields alongside everything
// else in the document, same shape as the existing `archivedAt`.
function withTimestamps(row) {
  const out = { ...row.data, updatedAt: row.updated_at.toISOString() };
  if (row.created_at) out.createdAt = row.created_at.toISOString();
  return out;
}

// created_at only exists on a database that's had db/schema.sql's migration
// applied to it (see that file — it's a one-time, run-it-yourself step, not
// something the app runs itself). Querying it against a database that
// hasn't been migrated yet fails outright ("column ... does not exist"),
// which would otherwise take the ENTIRE app down — every property read
// goes through here. Falling back to the plain query on that one specific
// error means a database that's behind the current schema.sql degrades to
// "no created date yet" (T.fmtDate(undefined) already renders as nothing)
// instead of a hard outage; run `npm run db:setup` against it whenever
// convenient to pick created_at up for real.
async function selectProperties(client, whereSql, params) {
  try {
    const { rows } = await client.query(
      `select data, created_at, updated_at from properties ${whereSql}`,
      params
    );
    return rows;
  } catch (err) {
    if (!/created_at/i.test(err.message)) throw err;
    const { rows } = await client.query(
      `select data, updated_at from properties ${whereSql}`,
      params
    );
    return rows;
  }
}

export async function listProperties() {
  return withClient(async (client) => {
    const rows = await selectProperties(client, "order by updated_at desc", []);
    return rows.map(withTimestamps);
  });
}

export async function getProperty(id) {
  return withClient(async (client) => {
    const rows = await selectProperties(client, "where id = $1", [id]);
    return rows[0] ? withTimestamps(rows[0]) : null;
  });
}

// Upsert by id — re-saving the same id updates the existing row.
// created_at is set once (the DEFAULT, on first insert) and deliberately
// left out of the `do update set` clause so it's never touched again.
// createdAt/updatedAt are stripped from `data` before storing — they're
// row-level metadata (see withTimestamps above), not part of the document;
// callers may well be handing back a copy they read (which now carries
// them), so this is what keeps the JSONB blob from also holding stale
// duplicates of what the row columns already track.
export async function upsertProperty(id, data) {
  const { createdAt, updatedAt, ...rest } = data;
  return withClient(async (client) => {
    await client.query(
      `insert into properties (id, data, updated_at)
       values ($1, $2, now())
       on conflict (id) do update set data = $2, updated_at = now()`,
      [id, rest]
    );
  });
}

// Permanently deletes one property. Returns true if a row was removed,
// false if no property with that id existed.
export async function deleteProperty(id) {
  return withClient(async (client) => {
    const { rowCount } = await client.query(
      "delete from properties where id = $1",
      [id]
    );
    return rowCount > 0;
  });
}

// Stores one uploaded material file's bytes. `id` is generated by the
// caller (crypto.randomUUID()) — it becomes part of the URL the property
// JSON's materials[category][].file field points at.
export async function saveMaterialFile({ id, propertyId, filename, contentType, data }) {
  return withClient(async (client) => {
    await client.query(
      `insert into material_files (id, property_id, filename, content_type, data)
       values ($1, $2, $3, $4, $5)`,
      [id, propertyId, filename, contentType || null, data]
    );
  });
}

// Fetches one material file's bytes + metadata for serving back over HTTP.
export async function getMaterialFile(id) {
  return withClient(async (client) => {
    const { rows } = await client.query(
      "select filename, content_type, data from material_files where id = $1",
      [id]
    );
    return rows[0] || null;
  });
}

// Runs arbitrary SQL (used by scripts/setup-db.mjs to apply db/schema.sql).
export async function runSql(sql) {
  return withClient((client) => client.query(sql));
}
